"""Project and shot domain models, disk store, and state transitions."""

from .models import (
    AgentContext,
    Project,
    PromptSections,
    RefRole,
    Shot,
    ShotRef,
    ShotVoiceRef,
    ShotStatus,
    voice_ref_signature,
)
from .layouts import (
    ClipTailFrameOrigin,
    LayoutBrief,
    LayoutReference,
    LayoutReviewStatus,
    LayoutSourceRef,
    layout_review_to_legacy,
    layout_prompt_signature,
    legacy_review_to_layout,
    mirror_legacy_layout_fields,
    selected_layout_prompt_context,
    sync_selected_layout_refs,
)
from .json_production import (
    JsonPictureRole,
    JsonProductionAudio,
    JsonProductionDocument,
    JsonProductionPicture,
    JsonProductionShot,
    JsonProductionStoredAsset,
    JsonProductionVideo,
    delete_json_production_asset,
    list_json_production_assets,
    load_json_production_asset,
    load_json_production_document,
    save_json_production_asset,
    save_json_production_document,
)
from .store import (
    create_project,
    list_projects,
    list_shots,
    load_project,
    load_shot,
    save_project,
    save_shot,
)
from .transitions import apply_transition, assert_h3_submittable

__all__ = [
    "AgentContext",
    "Project",
    "PromptSections",
    "RefRole",
    "Shot",
    "ShotRef",
    "ShotVoiceRef",
    "ShotStatus",
    "voice_ref_signature",
    "ClipTailFrameOrigin",
    "LayoutBrief",
    "LayoutReference",
    "LayoutReviewStatus",
    "LayoutSourceRef",
    "legacy_review_to_layout",
    "layout_review_to_legacy",
    "layout_prompt_signature",
    "mirror_legacy_layout_fields",
    "selected_layout_prompt_context",
    "sync_selected_layout_refs",
    "JsonPictureRole",
    "JsonProductionAudio",
    "JsonProductionDocument",
    "JsonProductionPicture",
    "JsonProductionShot",
    "JsonProductionStoredAsset",
    "JsonProductionVideo",
    "delete_json_production_asset",
    "list_json_production_assets",
    "load_json_production_asset",
    "load_json_production_document",
    "save_json_production_asset",
    "save_json_production_document",
    "apply_transition",
    "assert_h3_submittable",
    "create_project",
    "list_projects",
    "list_shots",
    "load_project",
    "load_shot",
    "save_project",
    "save_shot",
]
